version: '3'
services:
    db:
        container_name: postgres
        environment:
            # POSTGRES_DB: garnet
            POSTGRES_PASSWORD: garnet
            POSTGRES_USER: garnet
        image: postgres:13
        ports: 
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
    backend:
        container_name: garnet_backend
        init: true
        environment:
            GARNET_SERVICE_KEY: $GARNET_SERVICE_KEY
        # image: garnetlabs/garnet-oss-backend:latest
        build:
            context: ./backend
            dockerfile: dev.args.Dockerfile
            # args: 
        links:
            - db:db
        ports:
            - 8080:8080
        working_dir: /app
        command: sh -c "garnet run --service-key=${GARNET_SERVICE_KEY} -- npm run start:db"
    frontend:
        container_name: garnet_frontend
        # image: garnetlabs/garnet-oss-frontend:latest
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        ports:
            - 3000:3000
        working_dir: /app
        command: npm start
volumes:
    postgres-data: 